### ISSUE TITLE
Exception when using with gnupg-2.0.28

### ISSUE THREAD

**Issue by jurov** [Azelphur/pyMPEx#9]
```
gpg --status-fd 2 --no-tty --verify
[GNUPG:] NEWSIG
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "...python2.7/site-packages/gnupg.py", line 648, in _read_response
    result.handle_status(keyword, value)
  File "...python2.7/site-packages/gnupg.py", line 234, in handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'NEWSIG'
!!!WARNING!!!
Invalid Signature, do not trust this data.
```

python-gnupg library chokes on [GNUPG:] NEWSIG line that was not there in gnupg-2.0.26.

**Comment by Azelphur** [comment]
Hehe I agree python-gnupg is fairly derpy. I don't think there are any good alternatives however. If you know of any please point them out.

In my searching I did however find https://github.com/isislovecruft/python-gnupg which appears to be a maintenance fork of python-gnupg with a lot of issues fixed.

Could you test using the above library and see if the issue persists? if it works, perhaps we'll update our documentation/setup.py to point at this version instead.
